# -*- coding: utf-8 -*-
"""pandas_2021_AR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hAFhbYOsdF62YdRiXmrYyzhZgX08E93C
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# xlrd
# openyl

contagios= pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Intro_Pandas_2021.xlsx', sheet_name='Lineal')
#print(contagios.head())
#print(contagios.tail())
#print(contagios)
#contagios.plot(kind='scatter',x='Tiempo',y='Contagios',title= 'CONTAGIOS CUCUTA',color='y')
def lineal(x,m,b):
  y=m*x+b
  return y

def regresion_lineal(x,y): # x= 'Tiempo'  y= 'Contagios'
  sumax=x.sum()
  sumay=y.sum()
  n=x.count()
  sumaxy=(x*y).sum()
  sumaal2 =sumax**2
  sumax2=(x**2).sum()
  num =sumax*sumay - n*sumaxy
  den = sumaal2 -n*sumax2
  m = num/den
  mediax= x.mean()
  mediay= y.mean()
  b=mediay-m*mediax
  # c(t)= 0.50766*t + 1.9391
  return m,b

def graficar_regresion_lineal():
  m,b= regresion_lineal(contagios['Tiempo'],contagios['Contagios'])
  ejex= np.linspace(0,30,20)
  ejey= lineal(ejex,m,b)
  contagios.plot(kind='scatter',x='Tiempo',y='Contagios',title= 'CONTAGIOS CUCUTA',color='y')
  plt.plot(ejex,ejey)
  plt.show()


graficar_regresion_lineal()
#regresion_lineal(contagios['Tiempo'],contagios['Contagios'])